<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="asda1704po02529" ignored="0" name="Command line test" tests="10" failures="8" timestamp="09 Jul 2018 07:54:01 GMT" time="0.062" errors="0">
  <testcase name="Test10_Rotate_Array" time="0.009" classname="testquestion2.Test_MyCollection">
    <failure type="java.lang.AssertionError" message="expected [{Is, Always, A Fun., Sometimes, Automation, Testing}] but found [question2.MyCollection@9f70c54]">
      <![CDATA[java.lang.AssertionError: expected [{Is, Always, A Fun., Sometimes, Automation, Testing}] but found [question2.MyCollection@9f70c54]
at testquestion2.Test_MyCollection.Test10_Rotate_Array(Test_MyCollection.java:94)
... Removed 40 stack frames]]>
    </failure>
  </testcase> <!-- Test10_Rotate_Array -->
  <testcase name="Test1_Able_To_Add_New_Entry_In_Collection" time="0.0" classname="testquestion2.Test_MyCollection">
    <failure type="java.lang.AssertionError" message="Assertion Failed : Not able to add number 5 in collection expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Assertion Failed : Not able to add number 5 in collection expected [true] but found [false]
at testquestion2.Test_MyCollection.Test1_Able_To_Add_New_Entry_In_Collection(Test_MyCollection.java:16)
... Removed 37 stack frames]]>
    </failure>
  </testcase> <!-- Test1_Able_To_Add_New_Entry_In_Collection -->
  <testcase name="Test2_Duplicate_Entry_In_Collection" time="0.001" classname="testquestion2.Test_MyCollection"/>
  <testcase name="Test3_Get_Collection_Functionality" time="0.0" classname="testquestion2.Test_MyCollection">
    <failure type="java.lang.AssertionError" message="Assertion Failed : Not able to read collection expected [{}] but found [question2.MyCollection@61a485d2]">
      <![CDATA[java.lang.AssertionError: Assertion Failed : Not able to read collection expected [{}] but found [question2.MyCollection@61a485d2]
at testquestion2.Test_MyCollection.Test3_Get_Collection_Functionality(Test_MyCollection.java:32)
... Removed 39 stack frames]]>
    </failure>
  </testcase> <!-- Test3_Get_Collection_Functionality -->
  <testcase name="Test4_DoubleCapacity" time="0.001" classname="testquestion2.Test_MyCollection">
    <failure type="java.lang.AssertionError" message="Assertion Failed : Not able to add number in collection once it get fulled expected [{4,5,-4,-5,6}] but found [question2.MyCollection@7946e1f4]">
      <![CDATA[java.lang.AssertionError: Assertion Failed : Not able to add number in collection once it get fulled expected [{4,5,-4,-5,6}] but found [question2.MyCollection@7946e1f4]
at testquestion2.Test_MyCollection.Test4_DoubleCapacity(Test_MyCollection.java:41)
... Removed 39 stack frames]]>
    </failure>
  </testcase> <!-- Test4_DoubleCapacity -->
  <testcase name="Test5_Remove_Functionality_If_Entry_Already_Present" time="0.001" classname="testquestion2.Test_MyCollection">
    <failure type="java.lang.AssertionError" message="Assetion Failed : Not Able to delete entry from collection expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Assetion Failed : Not Able to delete entry from collection expected [true] but found [false]
at testquestion2.Test_MyCollection.Test5_Remove_Functionality_If_Entry_Already_Present(Test_MyCollection.java:50)
... Removed 37 stack frames]]>
    </failure>
  </testcase> <!-- Test5_Remove_Functionality_If_Entry_Already_Present -->
  <testcase name="Test6_Remove_Functionality_If_Collection_Is_Empty" time="0.001" classname="testquestion2.Test_MyCollection"/>
  <testcase name="Test7_Collection_Length_Functionality" time="0.0" classname="testquestion2.Test_MyCollection">
    <failure type="java.lang.AssertionError" message="expected [6] but found [0]">
      <![CDATA[java.lang.AssertionError: expected [6] but found [0]
at testquestion2.Test_MyCollection.Test7_Collection_Length_Functionality(Test_MyCollection.java:66)
... Removed 40 stack frames]]>
    </failure>
  </testcase> <!-- Test7_Collection_Length_Functionality -->
  <testcase name="Test8_Search_Functionality_If_Enrty_Exists" time="0.0" classname="testquestion2.Test_MyCollection">
    <failure type="java.lang.AssertionError" message="expected [1] but found [0]">
      <![CDATA[java.lang.AssertionError: expected [1] but found [0]
at testquestion2.Test_MyCollection.Test8_Search_Functionality_If_Enrty_Exists(Test_MyCollection.java:75)
... Removed 40 stack frames]]>
    </failure>
  </testcase> <!-- Test8_Search_Functionality_If_Enrty_Exists -->
  <testcase name="Test9_Search_Functionality_If_Enrty_Not_Exists" time="0.0" classname="testquestion2.Test_MyCollection">
    <failure type="java.lang.AssertionError" message="expected [-1] but found [0]">
      <![CDATA[java.lang.AssertionError: expected [-1] but found [0]
at testquestion2.Test_MyCollection.Test9_Search_Functionality_If_Enrty_Not_Exists(Test_MyCollection.java:84)
... Removed 40 stack frames]]>
    </failure>
  </testcase> <!-- Test9_Search_Functionality_If_Enrty_Not_Exists -->
</testsuite> <!-- Command line test -->
